import CMDGCondensedCM4P3C
import Mathlib.CategoryTheory.ObjectProperty.Local
import Mathlib.CategoryTheory.ObjectProperty.LimitsOfShape
import Mathlib.Condensed.Discrete.Module

/-!
# CMDG CM4-P3-D — local-object and coefficient-solidity reduction

P3-C identifies its residual tensor-Hom theorem exactly with the pinned
`CondensedMod.IsSolid` obligation. This fixture reduces that objectwise
solidity obligation further using the generic category-theoretic notion of an
object local with respect to a family of morphisms.

The new result is intentionally conditional at the final coefficient step:
solidity of an arbitrary product of copies of the discrete coefficient object
follows from solidity of one coefficient object, and an objectwise isomorphism
to such a product transports that result. No coefficient-solidity theorem is
assumed or manufactured here.
-/

namespace CMDG.CondensedCM4P3D

universe u v

open CategoryTheory Limits Opposite

/-- Exact lifted integral coefficient ring retained from CM4/P2/P3. -/
abbrev R := ULift.{u + 1} ℤ

/-- The actual pinned solidification morphism. -/
noncomputable abbrev solidification (X : Profinite.{u}) :=
  (Condensed.profiniteSolidification R).app X

/-- Ordinary categorical precomposition with the pinned solidification map. -/
noncomputable def homPrecomp (A : CondensedMod.{u} R) (X : Profinite.{u}) :
    (((Condensed.profiniteSolid R).obj X ⟶ A) →
      ((Condensed.profiniteFree R).obj X ⟶ A)) :=
  fun g => solidification X ≫ g

/-- The same precomposition function promoted to a morphism in `Type`. -/
noncomputable def homPrecompType (A : CondensedMod.{u} R) (X : Profinite.{u}) :
    ((Condensed.profiniteSolid R).obj X ⟶ A) ⟶
      ((Condensed.profiniteFree R).obj X ⟶ A) :=
  TypeCat.ofHom (homPrecomp A X)

/-- Yoneda precomposition is definitionally the ordinary Hom precomposition
function used by the locality predicate. -/
theorem yonedaPrecomp_eq_homPrecompType (A : CondensedMod.{u} R)
    (X : Profinite.{u}) :
    (yoneda.obj A).map (solidification X).op = homPrecompType A X := by
  rfl

/-- Pointwise bijectivity of ordinary Hom precomposition is exactly the
`IsIso` proposition appearing in the pinned `CondensedMod.IsSolid` field. -/
theorem homPrecomp_bijective_iff_isIso (A : CondensedMod.{u} R)
    (X : Profinite.{u}) :
    Function.Bijective (homPrecomp A X) ↔
      IsIso ((yoneda.obj A).map (solidification X).op) := by
  rw [yonedaPrecomp_eq_homPrecompType A X]
  simpa [homPrecompType] using
    (CategoryTheory.bijective_iff_isIso_ofHom (homPrecomp A X))

/-- The exact pinned solidity predicate is pointwise bijectivity of ordinary
precomposition with every profinite solidification map. -/
theorem isSolid_iff_pointwise_bijective (A : CondensedMod.{u} R) :
    CondensedMod.IsSolid R A ↔
      ∀ X : Profinite.{u}, Function.Bijective (homPrecomp A X) := by
  constructor
  · intro h X
    exact (homPrecomp_bijective_iff_isIso A X).mpr
      (h.isIso_solidification_map X)
  · intro h
    constructor
    intro X
    exact (homPrecomp_bijective_iff_isIso A X).mp (h X)

/-- Morphism property generated by the exact family of pinned solidification
maps. Locality for this property is the categorical form of solidity used
below to obtain limit closure. -/
noncomputable def solidificationProperty :
    MorphismProperty (CondensedMod.{u} R) :=
  ⨆ X : Profinite.{u}, MorphismProperty.single (solidification X)

/-- Locality with respect to the generated morphism property is exactly
pointwise bijectivity of solidification precomposition. -/
theorem isLocal_iff_pointwise_bijective (A : CondensedMod.{u} R) :
    solidificationProperty.isLocal A ↔
      ∀ X : Profinite.{u}, Function.Bijective (homPrecomp A X) := by
  change
    ((⨆ X : Profinite.{u}, MorphismProperty.single (solidification X)).isLocal A) ↔
      ∀ X : Profinite.{u}, Function.Bijective (homPrecomp A X)
  rw [MorphismProperty.isLocal_iSup]
  simp only [iInf_apply, iInf_Prop_eq]
  constructor
  · intro h X
    change Function.Bijective (fun g => solidification X ≫ g)
    exact
      (MorphismProperty.isLocal_single_iff_bijective (solidification X) A).mp (h X)
  · intro h X
    apply (MorphismProperty.isLocal_single_iff_bijective (solidification X) A).mpr
    have hx := h X
    change Function.Bijective (fun g => solidification X ≫ g) at hx
    exact hx

/-- Exact bridge: the pinned `CondensedMod.IsSolid` predicate is the generic
local-object predicate for the family of solidification maps. -/
theorem isSolid_iff_isLocal (A : CondensedMod.{u} R) :
    CondensedMod.IsSolid R A ↔ solidificationProperty.isLocal A :=
  (isSolid_iff_pointwise_bijective A).trans
    (isLocal_iff_pointwise_bijective A).symm

/-- The pinned solidity predicate is closed under an arbitrary categorical
limit because local objects for any morphism property are closed under limits
of every shape. -/
theorem isSolid_of_isLimit {J : Type v} [Category.{v} J]
    (F : J ⥤ CondensedMod.{u} R) (c : Cone F) (hc : IsLimit c)
    (hF : ∀ j : J, CondensedMod.IsSolid R (F.obj j)) :
    CondensedMod.IsSolid R c.pt := by
  rw [isSolid_iff_isLocal]
  apply CategoryTheory.ObjectProperty.prop_of_isLimit
    (P := solidificationProperty.isLocal) hc
  intro j
  exact (isSolid_iff_isLocal (F.obj j)).mp (hF j)

/-- In particular, an arbitrary product of solid condensed modules is solid
for this exact pinned predicate. -/
theorem isSolid_pi {I : Type v} (A : I → CondensedMod.{u} R) [HasProduct A]
    (hA : ∀ i : I, CondensedMod.IsSolid R (A i)) :
    CondensedMod.IsSolid R (∏ᶜ A) := by
  rw [isSolid_iff_isLocal]
  apply CategoryTheory.ObjectProperty.prop_pi
    (P := solidificationProperty.isLocal) A
  intro i
  exact (isSolid_iff_isLocal (A i)).mp (hA i)

/-- Solidity transports across objectwise isomorphism; this is proved through
locality rather than postulated as an extra solidity API. -/
theorem isSolid_of_iso {A B : CondensedMod.{u} R} (e : A ≅ B)
    (hA : CondensedMod.IsSolid R A) : CondensedMod.IsSolid R B := by
  rw [isSolid_iff_isLocal]
  exact CategoryTheory.ObjectProperty.prop_of_iso
    solidificationProperty.isLocal e
    ((isSolid_iff_isLocal A).mp hA)

/-- The discrete lifted-integer coefficient object whose solidity is the new
single-object residual after product closure. -/
noncomputable abbrev coefficientObject : CondensedMod.{u} R :=
  (CondensedMod.LocallyConstant.functor R).obj (ModuleCat.of R R)

/-- Exact remaining coefficient theorem, stated without assuming it. -/
def CoefficientResidualHomTheorem : Prop :=
  ∀ X : Profinite.{u}, Function.Bijective (homPrecomp (coefficientObject.{u}) X)

/-- The remaining coefficient Hom theorem is logically identical to solidity
of the discrete coefficient object. -/
theorem coefficientResidualHomTheorem_iff_isSolid :
    CoefficientResidualHomTheorem.{u} ↔
      CondensedMod.IsSolid R (coefficientObject.{u}) := by
  exact (isSolid_iff_pointwise_bijective (coefficientObject.{u})).symm

/-- Product closure removes the entire product step: once the coefficient
object is solid, every product of copies of it is solid. -/
theorem coefficientProduct_isSolid {I : Type v}
    [HasProduct (fun _ : I => coefficientObject.{u})]
    (hCoeff : CondensedMod.IsSolid R (coefficientObject.{u})) :
    CondensedMod.IsSolid R (∏ᶜ (fun _ : I => coefficientObject.{u})) := by
  apply isSolid_pi
  intro _
  exact hCoeff

/-- Any objectwise product presentation reduces solidity of that object to the
single coefficient-solidity theorem. The isomorphism may be chosen and need
not be natural in any external parameter. -/
theorem isSolid_of_iso_coefficientProduct {I : Type v}
    [HasProduct (fun _ : I => coefficientObject.{u})] {A : CondensedMod.{u} R}
    (e : A ≅ ∏ᶜ (fun _ : I => coefficientObject.{u}))
    (hCoeff : CondensedMod.IsSolid R (coefficientObject.{u})) :
    CondensedMod.IsSolid R A := by
  exact isSolid_of_iso e.symm (coefficientProduct_isSolid hCoeff)

/-- P3-C residual theorem reduction. If a chosen-basis objectwise product
presentation of `profiniteSolid S` is supplied, then the full P3-C residual
for `S` follows from the single coefficient-solidity theorem. No naturality of
`e` is claimed or required. -/
theorem residualHomTheorem_of_iso_coefficientProduct (S : Profinite.{u})
    {I : Type v} [HasProduct (fun _ : I => coefficientObject.{u})]
    (e : (Condensed.profiniteSolid R).obj S ≅
      ∏ᶜ (fun _ : I => coefficientObject.{u}))
    (hCoeff : CondensedMod.IsSolid R (coefficientObject.{u})) :
    CMDG.CondensedCM4P3C.ResidualHomTheorem S := by
  apply (CMDG.CondensedCM4P3C.residualHomTheorem_iff_isSolid S).mpr
  exact isSolid_of_iso_coefficientProduct e hCoeff

/-- Equivalent version with the exact remaining coefficient Hom theorem as
hypothesis. -/
theorem residualHomTheorem_of_product_and_coefficientResidual
    (S : Profinite.{u}) {I : Type v}
    [HasProduct (fun _ : I => coefficientObject.{u})]
    (e : (Condensed.profiniteSolid R).obj S ≅
      ∏ᶜ (fun _ : I => coefficientObject.{u}))
    (hCoeff : CoefficientResidualHomTheorem.{u}) :
    CMDG.CondensedCM4P3C.ResidualHomTheorem S := by
  apply residualHomTheorem_of_iso_coefficientProduct S e
  exact coefficientResidualHomTheorem_iff_isSolid.mp hCoeff

#check MorphismProperty.isLocal
#check MorphismProperty.isLocal_iSup
#check MorphismProperty.isLocal_single_iff_bijective
#check CategoryTheory.ObjectProperty.prop_of_isLimit
#check CategoryTheory.ObjectProperty.prop_pi
#check CategoryTheory.ObjectProperty.prop_of_iso
#check solidificationProperty
#check isSolid_iff_pointwise_bijective
#check isLocal_iff_pointwise_bijective
#check isSolid_iff_isLocal
#check isSolid_of_isLimit
#check isSolid_pi
#check isSolid_of_iso
#check coefficientObject
#check CoefficientResidualHomTheorem
#check coefficientResidualHomTheorem_iff_isSolid
#check coefficientProduct_isSolid
#check isSolid_of_iso_coefficientProduct
#check residualHomTheorem_of_iso_coefficientProduct
#check residualHomTheorem_of_product_and_coefficientResidual

#print axioms yonedaPrecomp_eq_homPrecompType
#print axioms homPrecomp_bijective_iff_isIso
#print axioms isSolid_iff_pointwise_bijective
#print axioms isLocal_iff_pointwise_bijective
#print axioms isSolid_iff_isLocal
#print axioms isSolid_of_isLimit
#print axioms isSolid_pi
#print axioms isSolid_of_iso
#print axioms coefficientResidualHomTheorem_iff_isSolid
#print axioms coefficientProduct_isSolid
#print axioms isSolid_of_iso_coefficientProduct
#print axioms residualHomTheorem_of_iso_coefficientProduct
#print axioms residualHomTheorem_of_product_and_coefficientResidual

end CMDG.CondensedCM4P3D
