import CMDGCondensedCM4P3GFiniteWindow

/-!
# CMDG CM4-P3-G Boolean finite-support extraction

This fixture packages the exact abstract slenderness step needed after the measure object has been
placed in basis coordinates: if an additive functional on an integer product has a locally constant
restriction to the Boolean cube, then its standard-coordinate coefficients vanish outside one
finite set. It also upgrades that finite-support statement to full finite-coordinate dependence
when every weighted Boolean restriction is locally constant.
-/

namespace CMDG.CondensedCM4P3G.FiniteSupport

open scoped Topology BigOperators

/-- Embed a Boolean coordinate vector into the corresponding `0/1` integer vector. -/
def boolToInt {ι : Type*} (x : ι → Bool) : ι → ℤ :=
  fun i => if x i then 1 else 0

/-- The Boolean vector supported on one coordinate. -/
def boolIndicator {ι : Type*} [DecidableEq ι] (i : ι) : ι → Bool :=
  fun j => if j = i then true else false

/-- The integer standard-coordinate vector. -/
def intIndicator {ι : Type*} [DecidableEq ι] (i : ι) : ι → ℤ :=
  fun j => if j = i then 1 else 0

/-- Weight a Boolean vector by an arbitrary integer coordinate vector. -/
def weightedBoolToInt {ι : Type*} (a : ι → ℤ) (x : ι → Bool) : ι → ℤ :=
  fun i => if x i then a i else 0

/-- Restrict an integer product vector to a finite coordinate set. -/
def finiteTruncation {ι : Type*} [DecidableEq ι]
    (a : ι → ℤ) (I : Finset ι) : ι → ℤ :=
  fun i => if i ∈ I then a i else 0

theorem boolToInt_boolIndicator {ι : Type*} [DecidableEq ι] (i : ι) :
    boolToInt (boolIndicator i) = intIndicator i := by
  funext j
  by_cases h : j = i <;> simp [boolToInt, boolIndicator, intIndicator, h]

theorem boolToInt_zero {ι : Type*} :
    boolToInt (fun _ : ι => false) = 0 := by
  funext i
  simp [boolToInt]

theorem weightedBoolToInt_one {ι : Type*} (x : ι → Bool) :
    weightedBoolToInt (fun _ => 1) x = boolToInt x := by
  funext i
  by_cases h : x i <;> simp [weightedBoolToInt, boolToInt, h]

theorem weightedBoolToInt_piecewise {ι : Type*} [DecidableEq ι]
    (a : ι → ℤ) (I : Finset ι) :
    weightedBoolToInt a (I.piecewise (fun _ => true) (fun _ => false)) =
      finiteTruncation a I := by
  funext i
  by_cases hi : i ∈ I <;> simp [weightedBoolToInt, finiteTruncation, hi]

theorem weightedBoolToInt_allTrue {ι : Type*} (a : ι → ℤ) :
    weightedBoolToInt a (fun _ => true) = a := by
  funext i
  simp [weightedBoolToInt]

theorem finiteTruncation_insert {ι : Type*} [DecidableEq ι]
    (a : ι → ℤ) (I : Finset ι) (i : ι) (hi : i ∉ I) :
    finiteTruncation a (insert i I) =
      (a i) • intIndicator i + finiteTruncation a I := by
  funext k
  by_cases hki : k = i
  · subst k
    simp [finiteTruncation, intIndicator, hi]
  · simp [finiteTruncation, intIndicator, hki]

/-- A finite truncation is literally the finite sum of its weighted standard-coordinate vectors. -/
theorem finiteTruncation_eq_sum {ι : Type*} [DecidableEq ι]
    (a : ι → ℤ) (I : Finset ι) :
    finiteTruncation a I = ∑ i ∈ I, (a i) • intIndicator i := by
  induction I using Finset.induction_on with
  | empty =>
      funext k
      simp [finiteTruncation]
  | @insert i I hi ih =>
      rw [finiteTruncation_insert a I i hi, ih]
      simp [hi]

/-- Boolean local constancy forces finite standard-coordinate support for an additive functional
on the full integer product. -/
theorem finite_support_of_bool_locallyConstant
    {ι : Type*} [DecidableEq ι]
    (L : (ι → ℤ) →+ ℤ)
    (f : LocallyConstant (ι → Bool) ℤ)
    (hf : ∀ x : ι → Bool, f x = L (boolToInt x)) :
    ∃ I : Finset ι, ∀ i ∉ I, L (intIndicator i) = 0 := by
  obtain ⟨I, hI⟩ :=
    CMDG.CondensedCM4P3G.FiniteWindow.locallyConstant_boolPi_zero_finiteWindow f
  refine ⟨I, ?_⟩
  intro i hi
  have hzero : f (boolIndicator i) = f (fun _ => false) := by
    apply hI
    intro j hj
    have hji : j ≠ i := by
      intro h
      subst j
      exact hi hj
    simp only [boolIndicator, if_neg hji]
  calc
    L (intIndicator i) = L (boolToInt (boolIndicator i)) :=
      congrArg L (boolToInt_boolIndicator i).symm
    _ = f (boolIndicator i) := (hf (boolIndicator i)).symm
    _ = f (fun _ => false) := hzero
    _ = L (boolToInt (fun _ : ι => false)) := hf (fun _ => false)
    _ = L 0 := congrArg L boolToInt_zero
    _ = 0 := map_zero L

/-- If every weighted Boolean restriction of an additive functional is locally constant, then
one finite coordinate set controls the functional on the entire integer product. This is the
precise finite-dependence statement needed in the coefficient mapping-out argument; it does not
assume that the product is generated by finitely supported vectors. -/
theorem finite_coordinate_dependence_of_weighted_bool_locallyConstant
    {ι : Type*} [DecidableEq ι]
    (L : (ι → ℤ) →+ ℤ)
    (hLC :
      ∀ a : ι → ℤ,
        ∃ f : LocallyConstant (ι → Bool) ℤ,
          ∀ t : ι → Bool,
            f t = L (weightedBoolToInt a t)) :
    ∃ I : Finset ι,
      ∀ a : ι → ℤ,
        (∀ i ∈ I, a i = 0) →
        L a = 0 := by
  obtain ⟨fOne, hfOne⟩ := hLC (fun _ => 1)
  have hfOne' : ∀ t : ι → Bool, fOne t = L (boolToInt t) := by
    intro t
    rw [hfOne t]
    exact congrArg L (weightedBoolToInt_one t)
  obtain ⟨I, hI⟩ := finite_support_of_bool_locallyConstant L fOne hfOne'
  refine ⟨I, ?_⟩
  intro a ha
  have htrunc : ∀ J : Finset ι, L (finiteTruncation a J) = 0 := by
    intro J
    induction J using Finset.induction_on with
    | empty =>
        have hz : finiteTruncation a ∅ = 0 := by
          funext k
          simp [finiteTruncation]
        rw [hz, map_zero]
    | @insert i J hi ih =>
        rw [finiteTruncation_insert a J i hi, map_add, ih, add_zero]
        by_cases hiI : i ∈ I
        · have hai : a i = 0 := ha i hiI
          have hz : (a i) • intIndicator i = 0 := by
            simp [hai]
          rw [hz, map_zero]
        · calc
            L ((a i) • intIndicator i) = (a i) • L (intIndicator i) :=
              AddMonoidHom.map_zsmul L (a i) (intIndicator i)
            _ = 0 := by simp [hI i hiI]
  obtain ⟨f, hf⟩ := hLC a
  have hpieces :
      ∀ J : Finset ι,
        f (J.piecewise (fun _ => true) (fun _ => false)) = 0 := by
    intro J
    calc
      f (J.piecewise (fun _ => true) (fun _ => false)) =
          L (weightedBoolToInt a
            (J.piecewise (fun _ => true) (fun _ => false))) :=
        hf _
      _ = L (finiteTruncation a J) :=
        congrArg L (weightedBoolToInt_piecewise a J)
      _ = 0 := htrunc J
  have hall :=
    CMDG.CondensedCM4P3G.locallyConstant_boolPi_allTrue_of_finsetPiecewise
      f 0 hpieces
  calc
    L a = L (weightedBoolToInt a (fun _ => true)) :=
      congrArg L (weightedBoolToInt_allTrue a).symm
    _ = f (fun _ => true) := (hf _).symm
    _ = 0 := hall

#print finiteTruncation_eq_sum
#print finite_support_of_bool_locallyConstant
#print finite_coordinate_dependence_of_weighted_bool_locallyConstant
#print axioms finiteTruncation_eq_sum
#print axioms finite_support_of_bool_locallyConstant
#print axioms finite_coordinate_dependence_of_weighted_bool_locallyConstant

end CMDG.CondensedCM4P3G.FiniteSupport
