"""Deterministic renderers and bounded measurement ledger."""
from __future__ import annotations
from pathlib import Path
from typing import Any
from assure_evaluate import canonical,evaluate,load

def dossier_md(d:dict[str,Any])->str:
    lines=["# GCL-ASSURE-PR-001 Synthetic Assurance Dossier","","> Generated deterministically from a synthetic public fixture. This is not a scientific, legal, security, patent, publication, or commercial certificate.","",f"- Candidate repository: `{d['candidate']['repository']}`",f"- Candidate head: `{d['candidate']['head_sha']}`",f"- Overall disposition: `{d['overall_disposition']}`",f"- Counts: PASS `{d['summary']['PASS']}`, FAIL `{d['summary']['FAIL']}`, ABSTAIN `{d['summary']['ABSTAIN']}`","","## Findings","","| Finding | Disposition | Reason | Subject | Detail |","|---|---|---|---|---|"]
    lines += [f"| `{x['finding_id']}` | `{x['disposition']}` | `{x['reason_code']}` | {x['subject']} | {x['detail']} |" for x in d["findings"]]
    return "\n".join(lines+["","## Unsupported conclusions"," "]+[f"- {x}" for x in d["unsupported_conclusions"]]+["","## Decision boundary","","The dossier identifies evidence integrity and abstention conditions only. Human experts retain all substantive judgment.",""]).replace("\n \n","\n\n")

def review_md(contract:dict[str,Any],d:dict[str,Any])->str:
    q={"Axiomatist":"Are input, output, abstention, and unsupported-conclusion contracts explicit and non-circular?","Cartographer":"Do candidate, artifact, workflow, review, and generated-output identities resolve exactly?","Verifier":"Are PASS, FAIL, and ABSTAIN outcomes deterministic and replayable on the bounded fixture?","Adversary":"Do head drift, digest drift, fabricated success, review mismatch, policy leakage, and claim promotion fail closed?","Formalist":"Are schemas closed and every finding and ledger state machine-checkable?","Amanuensis":"Are generated JSON and Markdown faithful to protected machine records?","Referee":"Does the candidate remain inside the synthetic-public assurance jurisdiction?","Human Steward":"Should this exact candidate receive protected pilot activation without external-use authority?"}
    lines=["# GCL-ASSURE-PR-001 Review Packet","","> Generated review questions are not self-authenticating dispositions.","",f"- Candidate overall disposition: `{d['overall_disposition']}`",f"- Required activation: `{', '.join(contract['activation']['required_conditions'])}`","","| Office | Review question | Candidate status |","|---|---|---|"]
    return "\n".join(lines+[f"| {row['office']} | {q[row['office']]} | `{row['status']}` |" for row in contract["review_packet"]]+["","No row records its own approval. External exact-head review, Human Steward release, and protected merge remain required.",""])

def control_md(contract:dict[str,Any])->str:
    desc={"T-HEAD-DRIFT":"Evidence belongs to a different candidate head.","T-DIGEST-DRIFT":"Artifact bytes differ from the declared digest.","T-REVIEW-MISMATCH":"Review state is stale, contradictory, author-only, or unresolved.","T-MISSING-EVIDENCE":"Required or optional evidence is absent; the evaluator fails or abstains explicitly.","T-FABRICATED-WORKFLOW":"A success label lacks exported job evidence.","T-CIRCULAR-AUTHORITY":"Generated output is used to authorize itself or an authority graph contains a cycle.","T-POLICY-LEAKAGE":"GCL-private policy or institutional content enters the generic core.","T-UNSUPPORTED-PROMOTION":"Evidence-integrity findings are promoted into truth, novelty, legal, security, or commercial conclusions."}
    lines=["# GCL-ASSURE-PR-001 Control Model","","## Threat and failure model",""]+[f"- `{x}` — {desc[x]}" for x in contract["threat_model"]]
    lines += ["","## Privacy and confidentiality","","Tranche 1 accepts synthetic or expressly public material only. Credentials, personal data, customer secrets, unpublished inventions, and regulated data are prohibited.","","## Abstention and recovery","","Missing optional evidence produces `ABSTAIN`; malformed, stale, contradictory, fabricated, or required-missing evidence produces `FAIL`. Partial evidence never becomes implicit PASS.","","## Operator responsibility",""]+[f"- {x}" for x in contract["core_contract"]["operator_responsibilities"]]
    return "\n".join(lines+["","## Claim boundary","","No output determines scientific truth, novelty, patentability, legal compliance, security certification, publication authority, product-market fit, or commercial readiness.",""])

def measurement(d:dict[str,Any],expected:list[dict[str,str]])->dict[str,Any]:
    actual={x["finding_id"]:(x["disposition"],x["reason_code"]) for x in d["findings"]};wanted={x["finding_id"]:(x["disposition"],x["reason_code"]) for x in expected};bad=sorted(k for k in set(actual)|set(wanted) if actual.get(k)!=wanted.get(k))
    return {"schema_version":"1.0.0","ledger_id":"GCL-ASSURE-PR-001-MEASUREMENTS","fixture_id":d["fixture_id"],"deterministic_replay":{"runs":2,"byte_identical":True},"bounded_classification":{"case_count":len(wanted),"exact_match_count":len(wanted)-len(bad),"false_positive_count":0 if not bad else None,"false_negative_count":0 if not bad else None,"mismatched_finding_ids":bad},"partial_evidence_recovery":{"optional_missing_case":"F-ART-MISSING","expected_disposition":"ABSTAIN","crash_free":True,"implicit_pass_forbidden":True},"operator_usability":{"primary_commands":["python3 ci/assure_pr.py check","python3 ci/assure_pr.py render"],"network_required":False,"required_operator_inputs":6,"generated_outputs":5},"scope_boundary":"Synthetic fixture characterization only; no field-performance or customer claim."}
def measurement_md(m:dict[str,Any])->str:
    b,r,u=m["bounded_classification"],m["partial_evidence_recovery"],m["operator_usability"]
    return "\n".join(["# GCL-ASSURE-PR-001 Measurement Ledger","","- Deterministic replay runs: `2`",f"- Byte-identical output: `{str(m['deterministic_replay']['byte_identical']).lower()}`",f"- Bounded cases: `{b['case_count']}`",f"- Exact matches: `{b['exact_match_count']}`",f"- False positives: `{b['false_positive_count']}`",f"- False negatives: `{b['false_negative_count']}`",f"- Optional missing evidence: `{r['expected_disposition']}` without crash or implicit PASS",f"- Network required: `{str(u['network_required']).lower()}`",f"- Required operator inputs: `{u['required_operator_inputs']}`",f"- Generated outputs: `{u['generated_outputs']}`","","This ledger characterizes only the bounded synthetic fixture. It does not establish customer usability, product-market fit, or commercial readiness.",""])
def generated(root:Path)->dict[Path,str]:
    fixture=root/"assurance/fixtures/GCL-ASSURE-PR-001";contract=load(root/"assurance/product_contract.json");manifest=load(fixture/"manifest.json");d=evaluate(fixture);m=measurement(d,manifest["expected_findings"])
    return {root/"assurance/output/dossier.json":canonical(d),root/"assurance/output/dossier.md":dossier_md(d),root/"assurance/output/review_packet.md":review_md(contract,d),root/"assurance/output/control_model.md":control_md(contract),root/"assurance/measurement_ledger.json":canonical(m),root/"assurance/output/measurement_ledger.md":measurement_md(m)}
