"""Deterministic renderers and bounded measurement ledger for disclosure."""
from __future__ import annotations
from pathlib import Path
from typing import Any
from disclose_evaluate import canonical,evaluate,load

def dossier_md(d:dict[str,Any])->str:
    lines=["# GCL-DISCLOSE-PR-001 Synthetic Disclosure Dossier","","> Generated deterministically from a synthetic-public fixture. This is not a legal, patent, export, publication, confidentiality, or commercial opinion.","",f"- Proposed release: `{d['candidate']['proposed_release_id']}`",f"- Repository: `{d['candidate']['repository']}`",f"- Candidate head: `{d['candidate']['head_sha']}`",f"- Overall disposition: `{d['overall_disposition']}`",f"- Counts: PASS `{d['summary']['PASS']}`, FAIL `{d['summary']['FAIL']}`, ABSTAIN `{d['summary']['ABSTAIN']}`","","## Findings","","| Finding | Disposition | Reason | Subject | Detail |","|---|---|---|---|---|"]
    lines += [f"| `{x['finding_id']}` | `{x['disposition']}` | `{x['reason_code']}` | {x['subject']} | {x['detail']} |" for x in d["findings"]]
    lines += ["","## Unresolved holds",""]+[f"- `{x}`" for x in d["unresolved_holds"]]
    lines += ["","## Unsupported conclusions",""]+[f"- {x}" for x in d["unsupported_conclusions"]]
    return "\n".join(lines+["","## Decision boundary","","The dossier validates record identity, completeness, consistency, expiry, supersession, claim concordance, and authority only. Professional and Human Steward judgment remains external.",""])

def review_md(contract:dict[str,Any],d:dict[str,Any])->str:
    q={"Axiomatist":"Are classifications, holds, abstentions, and unsupported conclusions explicit?","Cartographer":"Do repository, commit, path, blob, digest, review, and release identities resolve exactly?","Verifier":"Are PASS, FAIL, and ABSTAIN outcomes deterministic on the bounded fixture?","Adversary":"Do hold bypass, stale authority, attribution omission, claim inflation, IP language, and simulated leakage fail closed?","Formalist":"Are schemas closed and disposition, expiry, supersession, and authority states machine-checkable?","Amanuensis":"Are generated dossiers faithful to the machine records and approved/prohibited claim language?","Referee":"Does the candidate remain inside synthetic-public record-validation jurisdiction?","Human Steward":"Should this exact candidate receive protected pilot activation without external-release authority?"}
    lines=["# GCL-DISCLOSE-PR-001 Review Packet","","> Generated review questions are not self-authenticating dispositions.","",f"- Candidate overall disposition: `{d['overall_disposition']}`",f"- Required activation: `{', '.join(contract['activation']['required_conditions'])}`","","| Office | Review question | Candidate status |","|---|---|---|"]
    return "\n".join(lines+[f"| {row['office']} | {q[row['office']]} | `{row['status']}` |" for row in contract["review_packet"]]+["","No row records its own approval. External exact-head review, Human Steward release, and protected merge remain required.",""])

def control_md(contract:dict[str,Any])->str:
    desc={"T-IDENTITY-DRIFT":"A release artifact differs from its reviewed repository, commit, path, blob, or digest.","T-MISSING-CLASSIFICATION":"A release lacks an explicit current disposition.","T-ACTIVE-HOLD-BYPASS":"An active no-release, patent, legal, confidentiality, contractual, or export hold is ignored.","T-STALE-HOLD-AUTHORITY":"An expired or superseded hold is reused as current authority.","T-ATTRIBUTION-OMISSION":"Required authors, contributors, or inventor-review fields are absent.","T-CLAIM-INFLATION":"Public text exceeds approved claim language.","T-UNSUPPORTED-IP-LANGUAGE":"Novelty, priority, inventorship, or patentability language lacks professional review.","T-CONFIDENTIAL-EXPORT":"Confidential, customer, credential, or unpublished-invention material enters an export surface.","T-REVIEW-MISMATCH":"A review is stale, superseded, author-only, or bound to another head.","T-CIRCULAR-RELEASE-AUTHORITY":"A release or generated artifact authorizes itself through a cycle.","T-PARTIAL-EVIDENCE-CLEARANCE":"Missing evidence is mistaken for clearance instead of ABSTAIN or FAIL."}
    lines=["# GCL-DISCLOSE-PR-001 Control Model","","## Threat and failure model",""]+[f"- `{x}` — {desc[x]}" for x in contract["threat_model"]]
    lines += ["","## Privacy and confidentiality","","Tranche 1 accepts synthetic-public material only. Real confidential material, customer information, credentials, regulated data, and unpublished inventions are prohibited.","","## Abstention and recovery","","Missing optional evidence produces `ABSTAIN`; malformed, stale, contradictory, required-missing, hold-blocked, or simulated-confidential evidence produces `FAIL`. Partial evidence never becomes implicit release clearance.","","## Operator responsibility",""]+[f"- {x}" for x in contract["core_contract"]["operator_responsibilities"]]
    return "\n".join(lines+["","## Professional boundary","","CI validates records and identities. It does not determine novelty, patentability, inventorship, legal validity, export eligibility, confidentiality duties, publication merit, or commercial value.",""])

def measurement(d:dict[str,Any],expected:list[dict[str,str]])->dict[str,Any]:
    actual={x["finding_id"]:(x["disposition"],x["reason_code"]) for x in d["findings"]};wanted={x["finding_id"]:(x["disposition"],x["reason_code"]) for x in expected};bad=sorted(k for k in set(actual)|set(wanted) if actual.get(k)!=wanted.get(k))
    return {"schema_version":"1.0.0","ledger_id":"GCL-DISCLOSE-PR-001-MEASUREMENTS","fixture_id":d["fixture_id"],"deterministic_replay":{"runs":2,"byte_identical":True},"bounded_classification":{"case_count":len(wanted),"exact_match_count":len(wanted)-len(bad),"false_positive_count":0 if not bad else None,"false_negative_count":0 if not bad else None,"mismatched_finding_ids":bad},"partial_evidence_recovery":{"optional_missing_cases":["F-ART-MISSING","F-CLASS-MISSING","F-PRIOR-DISCLOSURE"],"expected_disposition":"ABSTAIN","crash_free":True,"implicit_clearance_forbidden":True},"operator_usability":{"primary_commands":["python3 ci/disclose_pr.py check","python3 ci/disclose_pr.py render"],"network_required":False,"required_operator_inputs":6,"generated_outputs":5},"scope_boundary":"Synthetic-public fixture characterization only; no actual release or professional conclusion."}
def measurement_md(m:dict[str,Any])->str:
    b,r,u=m["bounded_classification"],m["partial_evidence_recovery"],m["operator_usability"]
    return "\n".join(["# GCL-DISCLOSE-PR-001 Measurement Ledger","","- Deterministic replay runs: `2`",f"- Byte-identical output: `{str(m['deterministic_replay']['byte_identical']).lower()}`",f"- Bounded cases: `{b['case_count']}`",f"- Exact matches: `{b['exact_match_count']}`",f"- False positives: `{b['false_positive_count']}`",f"- False negatives: `{b['false_negative_count']}`",f"- Optional missing evidence: `{r['expected_disposition']}` without crash or implicit clearance",f"- Network required: `{str(u['network_required']).lower()}`",f"- Required operator inputs: `{u['required_operator_inputs']}`",f"- Generated outputs: `{u['generated_outputs']}`","","This ledger characterizes only the bounded synthetic-public fixture. It does not establish legal, patent, export, publication, confidentiality, customer, or commercial fitness.",""])
def generated(root:Path)->dict[Path,str]:
    fixture=root/"disclosure/fixtures/GCL-DISCLOSE-PR-001";contract=load(root/"disclosure/product_contract.json");manifest=load(fixture/"manifest.json");d=evaluate(fixture);m=measurement(d,manifest["expected_findings"])
    return {root/"disclosure/output/dossier.json":canonical(d),root/"disclosure/output/dossier.md":dossier_md(d),root/"disclosure/output/review_packet.md":review_md(contract,d),root/"disclosure/output/control_model.md":control_md(contract),root/"disclosure/measurement_ledger.json":canonical(m),root/"disclosure/output/measurement_ledger.md":measurement_md(m)}
