#!/usr/bin/env python3
"""Render the governed GCL portfolio pilot view from protected records."""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY = ROOT / "portfolio" / "pilot_registry.json"
DEFAULT_VIEW = ROOT / "docs" / "governance" / "GCL_PORTFOLIO_VIEW.md"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def metric_bounds(value: int | str, unknown_min: int = 0, unknown_max: int = 5) -> tuple[float, float]:
    if value == "unknown":
        return float(unknown_min), float(unknown_max)
    return float(value), float(value)


def advisory_interval(record: dict[str, Any], model: dict[str, Any]) -> tuple[float, float]:
    unknown_min = model["unknown_bounds"]["minimum"]
    unknown_max = model["unknown_bounds"]["maximum"]
    weights = model["benefit_weights"]

    def bounds(value: int | str) -> tuple[float, float]:
        return metric_bounds(value, unknown_min, unknown_max)

    importance = bounds(record["scientific_importance"])
    information = bounds(record["expected_information_gain"])
    leverage = bounds(record["institutional_leverage"])
    transfer = bounds(record["transfer_value"])
    publication = bounds(record["publication_value"])
    product = bounds(record["product_value"])
    readiness = bounds(record["execution_readiness"])
    probability = bounds(record["decisive_falsification"]["probability"])
    falsification_value = bounds(record["decisive_falsification"]["value"])

    benefit_min = (
        weights["scientific_importance"] * importance[0]
        + weights["expected_information_gain"] * information[0]
        + weights["institutional_leverage"] * leverage[0]
        + weights["transfer_value"] * transfer[0]
        + weights["falsification_value"] * probability[0] * falsification_value[0] / 5.0
        + weights["publication_value"] * publication[0]
        + weights["product_value"] * product[0]
    )
    benefit_max = (
        weights["scientific_importance"] * importance[1]
        + weights["expected_information_gain"] * information[1]
        + weights["institutional_leverage"] * leverage[1]
        + weights["transfer_value"] * transfer[1]
        + weights["falsification_value"] * probability[1] * falsification_value[1] / 5.0
        + weights["publication_value"] * publication[1]
        + weights["product_value"] * product[1]
    )

    cost_bounds = [bounds(record["cost"][name]) for name in ("compute", "labour", "review", "coordination")]
    dependency_risk = bounds(record["risk"]["dependency"])
    execution_risk = bounds(record["risk"]["execution"])

    denominator_min = (
        1.0
        + sum(item[0] for item in cost_bounds)
        + dependency_risk[0]
        + execution_risk[0]
    )
    denominator_max = (
        1.0
        + sum(item[1] for item in cost_bounds)
        + dependency_risk[1]
        + execution_risk[1]
    )

    lower = readiness[0] / 5.0 * benefit_min / denominator_max
    upper = readiness[1] / 5.0 * benefit_max / denominator_min
    return lower, upper


def display_metric(value: int | str) -> str:
    return str(value)


def render(registry: dict[str, Any]) -> str:
    lines = [
        "# GCL Portfolio Pilot View",
        "",
        "> Generated from `portfolio/pilot_registry.json`. Do not edit this file directly.",
        "",
        "This view is advisory only. It does not rank work, allocate resources, authorize execution, suspend work, or replace Human Steward or Council judgment.",
        "",
        "## Advisory model",
        "",
        f"- Model: `{registry['model']['model_id']}`",
        f"- Formula: `{registry['model']['formula']}`",
        "- Unknown values are evaluated across the declared 0–5 bounds and widen the interval.",
        "- Records are displayed in issue order, not by advisory value.",
        "",
        "## Pilot inventory",
        "",
        "| Work package | State | Importance | Readiness | Leverage | Information gain | Advisory interval | Next executable obligation |",
        "|---|---:|---:|---:|---:|---:|---:|---|",
    ]
    for record in sorted(registry["records"], key=lambda item: item["issue_number"]):
        lower, upper = advisory_interval(record, registry["model"])
        obligation = record["next_executable_obligation"].replace("|", "\\|")
        lines.append(
            "| "
            + f"[`{record['work_package_id']}`](https://github.com/grandchallenge/MATH-PROGRAMME/issues/{record['issue_number']})"
            + f" | {record['state']}"
            + f" | {display_metric(record['scientific_importance'])}"
            + f" | {display_metric(record['execution_readiness'])}"
            + f" | {display_metric(record['institutional_leverage'])}"
            + f" | {display_metric(record['expected_information_gain'])}"
            + f" | `{lower:.4f}–{upper:.4f}`"
            + f" | {obligation} |"
        )
    lines.extend(
        [
            "",
            "## Decision boundary",
            "",
            "The intervals expose model sensitivity; they are not dispositions. Any admission, pause, termination, resource commitment, publication, or promotion requires a separate protected Human or Council record.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    registry = load_json(DEFAULT_REGISTRY)
    output = render(registry)
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        if not DEFAULT_VIEW.is_file() or DEFAULT_VIEW.read_text(encoding="utf-8") != output:
            print("generated portfolio view is stale", file=sys.stderr)
            return 1
        print("generated portfolio view matches protected records")
        return 0
    DEFAULT_VIEW.write_text(output, encoding="utf-8")
    print(DEFAULT_VIEW)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
