#!/usr/bin/env python3
"""Render the bounded GCL synthesis report and review packet."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY = ROOT / "synthesis" / "pilot_registry.json"
DEFAULT_REPORT = ROOT / "docs" / "governance" / "GCL_SYNTHESIS_REPORT.md"
DEFAULT_REVIEW = ROOT / "docs" / "governance" / "GCL_SYNTHESIS_REVIEW_PACKET.md"


def load_registry(path: Path = DEFAULT_REGISTRY) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def render_report(registry: dict[str, Any]) -> str:
    lines = [
        "# GCL Synthesis Pilot Report",
        "",
        "> Generated from `synthesis/pilot_registry.json`. Do not edit this file directly.",
        "",
        "This report is advisory only. It does not establish equivalence, activate downstream work, promote claims, issue certification, or replace office and Human review.",
        "",
        "## Protected source artifacts",
        "",
        "| Source | Programme | Commit | Protected path | Blob |",
        "|---|---|---|---|---|",
    ]
    for source in registry["source_artifacts"]:
        lines.append(
            f"| `{source['source_ref']}` | `{source['programme_id']}` | "
            f"`{source['commit_sha']}` | `{source['path']}` | `{source['git_blob_sha1']}` |"
        )
    lines.extend(["", "## Transfer analysis", ""])
    for record in registry["transfer_records"]:
        consequence = record["bounded_executable_consequence"] or "None; analogy rejected."
        source_assumptions = "; ".join(record["source_assumptions"])
        target_assumptions = "; ".join(record["target_assumptions"])
        evidence = ", ".join(f"`{item}`" for item in record["evidence_links"])
        negative = (
            ", ".join(f"`{item}`" for item in record["negative_knowledge_links"])
            if record["negative_knowledge_links"]
            else "None."
        )
        lines.extend([
            f"### {record['transfer_id']} — {record['analysis_disposition']}",
            "",
            f"- Theme: `{record['theme']}`",
            f"- Source: `{record['source_ref']}`",
            f"- Target: `{record['target']['programme_id']}` / issue #{record['target']['issue_number']}",
            f"- Target obligation: {record['target']['obligation']}",
            f"- Shared abstraction: {record['shared_abstraction']}",
            f"- Source assumptions: {source_assumptions}",
            f"- Target assumptions: {target_assumptions}",
            f"- Transferable: {record['transferable_component']}",
            f"- Non-transferable: {record['non_transferable_component']}",
            f"- Expected value: {record['expected_value']}",
            f"- Evidence: {evidence}",
            f"- Negative-knowledge links: {negative}",
            f"- Bounded consequence: {consequence}",
            f"- Falsifying test: {record['falsifying_test']}",
        ])
        if record["rejection_reason"]:
            lines.append(f"- Rejection reason: {record['rejection_reason']}")
        lines.append("")
    lines.extend(["## Contradictions and duplication", ""])
    for record in registry["contradiction_records"]:
        source_refs = ", ".join(f"`{item}`" for item in record["source_refs"])
        lines.extend([
            f"### {record['record_id']} — {record['disposition']}",
            "",
            f"- Kind: `{record['kind']}`",
            f"- Theme: `{record['theme']}`",
            f"- Sources: {source_refs}",
            f"- Statement A: {record['statement_a']}",
            f"- Statement B: {record['statement_b']}",
            f"- Required action: {record['required_action']}",
            f"- Prohibited collapse: {record['must_not_do']}",
            "",
        ])
    lines.extend([
        "## Decision boundary",
        "",
        "Accepted bounded transfers authorize only their recorded validator or review consequence. Rejected analogies carry no executable authority. Contradictions remain explicit. Downstream activation, publication, certification, novelty, patentability, product, and commercial decisions require separate protected dispositions.",
        "",
    ])
    return "\n".join(lines)


def render_review_packet(registry: dict[str, Any]) -> str:
    lines = [
        "# GCL Synthesis Pilot Review Packet",
        "",
        "> Generated from `synthesis/pilot_registry.json`. Office entries are review questions, not self-authenticating dispositions.",
        "",
        f"- Registry: `{registry['registry_id']}`",
        f"- Work package issue: #{registry['authority']['work_package_issue']}",
        f"- Portfolio prerequisite merge: `{registry['authority']['portfolio_merge']}`",
        "",
        "## Office review matrix",
        "",
        "| Office | Review question | Candidate status |",
        "|---|---|---|",
    ]
    for item in registry["review_packet"]:
        lines.append(f"| {item['office']} | {item['review_question']} | `{item['status']}` |")
    lines.extend([
        "",
        "## Required activation sequence",
        "",
        "1. External exact-head review.",
        "2. Explicit Human Steward release for the exact candidate head.",
        "3. Protected expected-head merge.",
        "",
        "No row in this packet records its own approval.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    registry = load_registry()
    DEFAULT_REPORT.write_text(render_report(registry), encoding="utf-8")
    DEFAULT_REVIEW.write_text(render_review_packet(registry), encoding="utf-8")
    print("rendered synthesis report and review packet")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
