#!/usr/bin/env python3
from __future__ import annotations

import json
from fractions import Fraction
from math import comb

RAW_WEIGHT1 = [
    "H_k_1", "H_l_1", "H_kl_1", "H_nk_1", "H_nl_1",
    "H_nmk_1", "H_nml_1", "H_nkl_1",
]

NAMED_WEIGHT1 = [
    "A_k_1", "A_l_1", "B_k_1", "B_l_1", "C_1",
    "H_k_1", "H_l_1", "H_kl_1",
]

# Rows express the named letters in RAW_WEIGHT1 order.  The transformation is
# triangular after adjoining the three retained raw local letters, hence rank 8.
NAMED_TO_RAW = {
    "A_k_1":  [-1, 0, 0, 1, 0, 0, 0, 0],
    "A_l_1":  [0, -1, 0, 0, 1, 0, 0, 0],
    "B_k_1":  [-1, 0, 0, 0, 0, 1, 0, 0],
    "B_l_1":  [0, -1, 0, 0, 0, 0, 1, 0],
    "C_1":    [0, 0, -1, 0, 0, 0, 0, 1],
    "H_k_1":  [1, 0, 0, 0, 0, 0, 0, 0],
    "H_l_1":  [0, 1, 0, 0, 0, 0, 0, 0],
    "H_kl_1": [0, 0, 1, 0, 0, 0, 0, 0],
}

AFFINE_ARGUMENTS = ["k", "l", "k+l", "n+k", "n+l", "n-k", "n-l", "n+k+l"]


def harmonic(m: int, r: int = 1) -> Fraction:
    return sum((Fraction(1, j**r) for j in range(1, m + 1)), Fraction(0))


def kernel(n: int, k: int, l: int) -> int:
    return (
        comb(n + k, n) * comb(n, k) ** 2
        * comb(n + l, n) * comb(n, l) ** 2
        * comb(n + k + l, n)
    )


def recurrence_coefficients(n: int) -> tuple[int, int, int, int]:
    a0 = lambda x: 41218*x**3 + 198849*x**2 + 320790*x + 173057
    b8 = lambda x: (
        3874492*x**8 + 59373972*x**7 + 394148190*x**6 + 1481084196*x**5
        + 3447878810*x**4 + 5095855458*x**3 + 4673546679*x**2
        + 2433871008*x + 551502039
    )
    b9 = lambda x: (
        48802112*x**9 + 967468896*x**8 + 8488000862*x**7 + 43246197636*x**6
        + 140983768422*x**5 + 304912330849*x**4 + 437406946975*x**3
        + 401272692378*x**2 + 213593890911*x + 50257929339
    )
    return (
        (n + 1)**5 * (n + 2) * a0(n + 1),
        -2 * (n + 2) * b8(n),
        -2 * b9(n),
        2 * (n + 3)**5 * (2*n + 5) * a0(n),
    )


def summed_hk(n: int) -> Fraction:
    total = Fraction(0)
    for k in range(n + 1):
        hk = harmonic(k)
        for l in range(n + 1):
            total += kernel(n, k, l) * hk
    return total


def rank_over_q(rows: list[list[int]]) -> int:
    a = [[Fraction(x) for x in row] for row in rows]
    if not a:
        return 0
    m, n = len(a), len(a[0])
    r = 0
    for c in range(n):
        pivot = next((i for i in range(r, m) if a[i][c]), None)
        if pivot is None:
            continue
        a[r], a[pivot] = a[pivot], a[r]
        q = a[r][c]
        a[r] = [x / q for x in a[r]]
        for i in range(m):
            if i != r and a[i][c]:
                q = a[i][c]
                a[i] = [x - q*y for x, y in zip(a[i], a[r])]
        r += 1
        if r == m:
            break
    return r


def result() -> dict:
    tangent_rank = rank_over_q([NAMED_TO_RAW[name] for name in NAMED_WEIGHT1])
    y = [summed_hk(j) for j in range(4)]
    c = recurrence_coefficients(0)
    obstruction = sum(Fraction(ci) * yi for ci, yi in zip(c, y))
    assert tangent_rank == 8
    assert y == [Fraction(0), Fraction(16), Fraction(3564), Fraction(3214312, 3)]
    assert obstruction == 92296128886152

    return {
        "operation": "OZ-RT-BZ-T3-009",
        "route": "DIRECT_T3_DISCRETE_RESIDUAL_CERT_001",
        "subroute": "QROW_SMALL_PARAMETER_DEFORMATION_TEST_001",
        "status": "SMALL_PARAMETER_QROW_AUTOMATIC_DIFFERENTIATION_ROUTE_REJECTED",
        "gamma_deformation": {
            "factor": "Phi_m(z)=Gamma(m+1+z)/(Gamma(m+1)*Gamma(1+z))",
            "log_derivative_rule": "d^r/dz^r log Phi_m(z)|_0=(-1)^(r-1)*(r-1)!*H_m^(r)",
            "affine_argument_families": AFFINE_ARGUMENTS,
            "parameter_count_to_generate_full_weight1_tangent_space": 8,
            "weight1_tangent_rank": tangent_rank,
            "algebraic_generation": "All 22 retained one-body atoms are generated by derivatives of these eight Gamma factors through order four.",
        },
        "dimension_obstruction": {
            "named_weight1_letters": NAMED_WEIGHT1,
            "raw_weight1_coordinates": RAW_WEIGHT1,
            "rank": tangent_rank,
            "conclusion": "Any ordinary first-order deformation with fewer than eight independent parameters cannot generate the full 22-atom module.",
        },
        "fixed_qrow_operator_obstruction": {
            "tested_direction": "H_k_1",
            "sequence": "Y_Hk(n)=sum_{k,l=0}^n T(n,k,l)*H_k",
            "Y_n_0_through_3": [str(x) for x in y],
            "recurrence_coefficients_at_n0": list(c),
            "exact_LBZ_Y_at_n0": str(obstruction),
            "nonzero": True,
            "logic": "If a full-rank parameterized Q-row identity with the protected fixed recurrence operator existed, differentiating in every tangent direction would force L_BZ[Y]=0. Since H_k lies in that tangent span and L_BZ[Y_Hk](0) is nonzero, no such full-rank deformation exists.",
        },
        "scope": "This rejects automatic parameter differentiation of a parameterized kernel certificate with the protected fixed recurrence operator as a generator of the full 22-atom module. It does not exclude parameter-dependent recurrence coefficients or deformation factors followed by new correction certificates; those are new certificate problems, not automatic consequences of the admitted Q-row identity.",
        "next_route": "STRUCTURED_ONE_BODY_LETTER_SPLIT_HOLONOMIC_001",
        "proof_effect": "NONE",
        "promotion_effect": "NONE",
        "t3_status": "OPEN_WITH_CHARACTERIZED_BLOCKER",
    }


if __name__ == "__main__":
    print(json.dumps(result(), indent=2, sort_keys=True))
